package net.multiplemonomials.eer.configuration;

import java.io.File;
import java.io.Serializable;

import net.minecraftforge.common.config.Configuration;

public class SerializableConfiguration extends Configuration implements Serializable
{

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 1531202563816051410L;

	
	//type of configuration
	public ReceivedConfigAction _configType;
	
	public SerializableConfiguration(File file)
	{
		super(file);
	}
}
